<!DOCTYPE table [
<!ELEMENT table (tuple)*>
<!ATTLIST table name CDATA #REQUIRED>
<!ELEMENT tuple (table | tuple | atom)*>
<!ATTLIST tuple name CDATA #IMPLIED>
<!ELEMENT atom (#PCDATA)*>
<!ATTLIST atom name CDATA #REQUIRED>
<!ATTLIST atom type CDATA "text">
<!ATTLIST atom size CDATA "short">
]>
<?schema table           ecatalogue
    text short      ObjObjectDiscipline
    text short      ObjCatalogueNumber
    text long       ObjObjectName
    text long       ObjObjectType
    table           ObjModel_tab
      text long       ObjModel
    end
    text short      ObjSerialNumber
    text long       ObjObjectAKA
    text long       ObjModelUserName
    text short      ObjPartNo
    integer         ObjPartNoSum
    table           ArtLexRank_tab
      integer         ArtLexRank
    end
    table           ArtLexGroup_tab
      text short      ArtLexGroup
    end
    table           ArtLexCategory_tab
      text short      ArtLexCategory
    end
    table           ArtLexSubCategory_tab
      text short      ArtLexSubCategory
    end
    text short      ObjManufactureDate
    integer         ObjManufactureDateFrom
    integer         ObjManufactureDateTo
    tuple           ObjManufacturerRef
      text short      NamOrganisation
      text short      NamOrganisationAcronym
      text short      AddPhysCity
      text short      AddPhysCountry
      text short      AddPhysState
    end
    tuple           ObjDistributorRef
      text short      NamOrganisation
      text short      NamOrganisationAcronym
      text short      AddPhysCity
      text short      AddPhysCountry
      text short      AddPhysState
      text long       AddPhysStreet
    end
    text long       ArtConCanada
    text long       ArtConFunction
    text long       ArtConTechnical
    text long       ArtConPeriod
    text long       ArtConCountry
    text long       ArtConProvinceState
    text long       ArtConAreaNotes
    table           ArtCompWandDMeasurement_tab
      text short      ArtCompWandDMeasurement
    end
    table           MulMultiMediaRef_tab
      table           DocIdentifier_tab
        text short      DocIdentifier
      end
    end
    text long       ArtDetMissing
    text long       ArtDetFinish
    text long       ArtDetDecoration
    text long       CstmcNotWeb
    text long       CstmcNotExhibit
    text long       NotNotes
    text short      ArtRefWorksheet
    text short      ArtRefCollection
    text short      ArtRefManual
    table           ArtRefPatents_tab
      text long       ArtRefPatents
    end
    text short      ArtRefSuppInfo
    text short      ArtRefOversized
    text short      ArtRefManual
    text short      ArtRefStillImages
    text short      ArtRefNumberRange
    text short      ArtRefArticleNumber
    text short      ArtRefMultimedia
    text short      ArtRefExternalDoc
    table           ArtRefImage_tab
      text short      ArtRefImage
    end
    table           ArtRefReferences_tab
      text long       ArtRefReferences
    end
    tuple           LocCurrentLocationRef
      text short      LocLevel1
    end
    text short      LocIndependentlyMoveable
    date            AssAssessmentDate
    text short      AssConditionReport
    text long       AssOilCoolantEtc
    text long       AssActionRequired
    text long       AssActionTaken
    text short      AssOperable
    text short      AssRestored
    text long       AssHazards
    table           ArtCompWandDValue_tab
      text long       ArtCompWandDValue
    end
    table           ArtCompWandDUnit_tab
      text short      ArtCompWandDUnit
    end
    text long       ArtCompGeneralDescription
    table           ArtCompMaterialCHINGeneral_tab
      text long       ArtCompMaterialCHINGeneral
    end
    table           ArtCompMaterialCHINSpecific_tab
      text long       ArtCompMaterialCHINSpecific
    end
    text short      ConConditionStatus
    date            ConDateChecked
    text long       ConConditionDetails
    text long       ConHandlingInstructions
    text short      CstmcAdmAcquisitionProposal
    table           InfStatus_tab
      text short      InfStatus
    end
    table           InfComments0
      text long       InfComments
    end
    table           InfInspectionDate0
      date            InfInspectionDate
    end
    table           StaStable_tab
      text short      StaStable
    end
    table           StaInspectionDate0
      date            StaInspectionDate
    end
    table           StaComments0
      text long       StaComments
    end
    text short      SrcCulturalProperty
    text short      SrcLotAcquisition
    text long       SrcOtherNos
    text short      SrcPreviousCstmcNos
  end
?>
<!-- Data -->
<table name="ecatalogue">
  <!-- Row 1 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1971.0228</atom>
    <atom name="ObjObjectName">Recorder, drum;:;Tambour enregistreur</atom>
    <atom name="ObjObjectType">ASTRONOMICAL/PHOTO</atom>
    <atom name="ObjSerialNumber">92632</atom>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">001</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Astronomy;:;Astronomie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Research;:;Recherche</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Non-analytical instruments;:;Instruments non analyse</atom>
      </tuple>
    </table>
    <atom name="ObjManufactureDate">between;:;entre</atom>
    <atom name="ObjManufactureDateFrom">1960</atom>
    <atom name="ObjManufactureDateTo">1969</atom>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Watts</atom>
      <atom name="NamOrganisationAcronym">Watts</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtConPeriod">PROBABLY USED IN THE 1960S</atom>
    <atom name="ArtConCountry">Canada</atom>
    <atom name="ArtConAreaNotes">ACCORDING TO BOX LABELS THIS ONE USED IN QUEBEC AND OTTAWA</atom>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1971.0228.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1971.0228.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetMissing">

From CA of 12/06/2001 by Matthew Bruce: No - appears complete</atom>
    <atom name="ArtDetFinish">BLACK GLOSS PAINT ON CASE AND DRUM; WHITE PRINTING/ OUTSIDE OF BOX PAINTED PALE GREEN GLOSS/ SOME RUST EVIDENT</atom>
    <atom name="NotNotes">COMES IN SHIPPING CASE LABELLED 'DOMINION OBSERVATORY'</atom>
    <atom name="ArtRefCollection">DOMINION OBSERVATORY</atom>
    <atom name="ArtRefSuppInfo">Yes;:;Oui</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Colour negative;:;N&#233;gatif en couleur</atom>
      </tuple>
    </table>
    <table name="ArtRefReferences_tab">
      <tuple>
        <atom name="ArtRefReferences">Museum Documents in Supp. Info.</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2421</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssAssessmentDate">2001-12-06</atom>
    <atom name="AssConditionReport">Yes;:;Oui</atom>
    <atom name="AssOilCoolantEtc">Not applicable.</atom>
    <atom name="AssActionRequired">dust and vacuum; wrap artifact in microfoam and block-up to prevent rocking around in case</atom>
    <atom name="AssActionTaken">dusted and vacuumed; padded and wrapped</atom>
    <atom name="AssOperable">No;:;Non</atom>
    <atom name="AssRestored">No;:;Non</atom>
    <atom name="AssHazards">No</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">045.8</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">015.2</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">015.2</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">STEEL CASE WITH LID, AND STEEL DRUM; PAPER ON DRUM; WOODEN BOX WITH METAL HARDWARE</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">wood;:;bois</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">paper;:;papier</atom>
      </tuple>
    </table>
    <table name="ArtCompMaterialCHINSpecific_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">steel;:;acier</atom>
      </tuple>
    </table>
    <table name="InfStatus_tab">
      <tuple>
        <atom name="InfStatus">No;:;Non</atom>
      </tuple>
    </table>
    <table name="InfComments0">
      <tuple>
        <atom name="InfComments">none</atom>
      </tuple>
    </table>
    <table name="InfInspectionDate0">
      <tuple>
        <atom name="InfInspectionDate">2001-12-06</atom>
      </tuple>
    </table>
    <table name="StaStable_tab">
      <tuple>
        <atom name="StaStable">Yes;:;Oui</atom>
      </tuple>
    </table>
    <table name="StaInspectionDate0">
      <tuple>
        <atom name="StaInspectionDate">2001-12-06</atom>
      </tuple>
    </table>
    <table name="StaComments0">
      <tuple>
        <atom name="StaComments">Stable Comments:  appears stable :: Deterioration Notes:  deteriorated padding/foam has been deposited on the artifact and cross linked; signs of water damage: exterior stained, corrosion on case and hardware, dirty; numerous abrasions; cross linked adhesive tape; nicks in edge of flywheel; case bent in near seam; Interior is dusty, coated in small shreds of red rubber(?) from parts inside drum; springs on either side of drum covered in white corrosion; film on drum is light damaged on one half of circumference, and scuffed/abraded where it folds into the drum; localized abrasions on drum edges; greasy residue inside case seam. BOX: water damage and staining; hardware corroded; localized abrasions; paint loss; cross linked adhesive labels; deteriorated foam padding on inner surfaces; black stains on inside bottom; dirty overall</atom>
      </tuple>
    </table>
    <atom name="SrcCulturalProperty">no;:;non</atom>
  </tuple>
  <!-- Row 2 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1974.0723</atom>
    <atom name="ObjObjectName">Telescope;:;T&#233;lescope</atom>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">001</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Astronomy;:;Astronomie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Observation equipment;:;&#201;quipement d'observation</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Optical telescopes;:;T&#233;lescopes optiques</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1974.0723.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1974.0723.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtRefSuppInfo">No;:;Non</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">LOST</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
    <atom name="AssOperable">No;:;Non</atom>
    <atom name="AssRestored">No;:;Non</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">000.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">000.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">000.0</atom>
      </tuple>
    </table>
  </tuple>
  <!-- Row 3 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">2000.0121</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">SPEEDOMAX/A</atom>
      </tuple>
    </table>
    <atom name="ObjSerialNumber">668631</atom>
    <atom name="ObjPartNo">002</atom>
    <atom name="ObjPartNoSum">002</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Physics;:;Physique</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexGroup">Chemistry;:;Chimie</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexGroup">Astronomy;:;Astronomie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Light &amp; electromagnetic radiation;:;Lumi&#232;re et radiation &#233;lectromagn&#233;tique</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexCategory">Test-measurement equipment;:;&#201;quipement d'essai et mesure</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexCategory">Research;:;Recherche</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Analytical instruments &amp; equipment;:;Instruments d'analyse et &#233;quipement</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexSubCategory">Analytical equipment &amp; instruments;:;&#201;quipement et instruments d'analyse</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexSubCategory">Analytical equipment &amp; instruments;:;&#201;quipement et instruments d'analyse</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2000.0121.002.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2000.0121.002.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetFinish">BLACK PAINTED RACK &amp; CASINGS; METALLIC DOOR HANDLES &amp; PARTS; COLOURLESS TRANSPARENT WINDOW; WHITE PAPER; BLACK POWER CORD</atom>
    <atom name="ArtDetDecoration">BLACK &amp; METALLIC STRIPED METAL PANELS ABOVE &amp; BELOW WINDOW</atom>
    <table name="ArtRefPatents_tab">
      <tuple>
        <atom name="ArtRefPatents">.2 U.S. PATENT NOS. 1820212 (1931), 2162469 (1939); TRADE MARK REGISTERED U.S. PATENT OFFICE</atom>
      </tuple>
    </table>
    <atom name="ArtRefSuppInfo">Yes;:;Oui</atom>
    <atom name="ArtRefNumberRange">2000.0117-2000.0123</atom>
    <atom name="ArtRefArticleNumber">6381-391</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <table name="ArtRefReferences_tab">
      <tuple>
        <atom name="ArtRefReferences">1) ACQUISITION PROPOSAL BY R.C. BROOKS (IN S.I. 2000.0117)</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">2) HARRISON, G. ET AL, "PRACTICAL SPECTOSCOPY", 1948. PP. 358-359 (SEE ILLUSTRATION P. 358 OF L&amp;N MICRODENSITOMETER)</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">3) LOEBL, H., "MICRODENSITOMETER" IN BUD, R. &amp; WARNER, D. "INSTRUMENTS OF SCIENCE", 1998, PP. 377-379 [Q 184.5 I57 1998] (.2-.3 IN S.I.)</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2475</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
    <atom name="ArtCompGeneralDescription">METAL CASINGS &amp; RACK; SYNTHETIC PARTS; GLASS WINDOW; PAPER CHART</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">synthetic;:;synth&#233;tique</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">glass;:;verre</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">paper;:;papier</atom>
      </tuple>
    </table>
    <atom name="SrcCulturalProperty">no;:;non</atom>
  </tuple>
  <!-- Row 4 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">2008.0204</atom>
    <atom name="ObjObjectName">Holder, film;:;Porte-film</atom>
    <atom name="ObjObjectType">sheet</atom>
    <atom name="ObjPartNo">011</atom>
    <atom name="ObjPartNoSum">019</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Astronomy;:;Astronomie</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexGroup">Photography;:;Photographie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Research;:;Recherche</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexCategory">Still camera parts;:;Pi&#232;ces d'appareil-photo</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Parts &amp; accessories;:;Pi&#232;ces et accessoires</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexSubCategory">Backs;:;Dos de boitier</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Rhaco</atom>
      <atom name="NamOrganisationAcronym">Rhaco</atom>
    </tuple>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Thickness;:;&#233;paisseur</atom>
      </tuple>
    </table>
    <atom name="ArtDetFinish">Painted glossy black</atom>
    <atom name="NotNotes">Number breakdown: .1 camera; .2 lens cap; .3-.12 film holders; .14-.15 cylindrical brass bars; .16-.18 screws; .19 box with attached lid (two pieces broken from lid and marked as parts)</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2421</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">015.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">010.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">000.4</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">Ferrous metal</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
    </table>
    <atom name="ConConditionStatus">Fair;:;Moyenne</atom>
    <atom name="ConDateChecked">2011-03-09</atom>
    <atom name="SrcLotAcquisition">yes;:;oui</atom>
  </tuple>
  <!-- Row 5 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">2008.0204</atom>
    <atom name="ObjObjectName">Holder, film;:;Porte-film</atom>
    <atom name="ObjObjectType">sheet</atom>
    <atom name="ObjPartNo">012</atom>
    <atom name="ObjPartNoSum">019</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Astronomy;:;Astronomie</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexGroup">Photography;:;Photographie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Research;:;Recherche</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexCategory">Still camera parts;:;Pi&#232;ces d'appareil-photo</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Parts &amp; accessories;:;Pi&#232;ces et accessoires</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexSubCategory">Backs;:;Dos de boitier</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Rhaco</atom>
      <atom name="NamOrganisationAcronym">Rhaco</atom>
    </tuple>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Thickness;:;&#233;paisseur</atom>
      </tuple>
    </table>
    <atom name="ArtDetFinish">Painted glossy black</atom>
    <atom name="NotNotes">Number breakdown: .1 camera; .2 lens cap; .3-.12 film holders; .14-.15 cylindrical brass bars; .16-.18 screws; .19 box with attached lid (two pieces broken from lid and marked as parts)</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2421</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">015.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">010.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">000.4</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">Ferrous metal</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
    </table>
    <atom name="ConConditionStatus">Fair;:;Moyenne</atom>
    <atom name="ConDateChecked">2011-03-09</atom>
    <atom name="SrcLotAcquisition">yes;:;oui</atom>
  </tuple>
  <!-- Row 6 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">2008.0204</atom>
    <atom name="ObjObjectName">Screw;:;Vis</atom>
    <atom name="ObjPartNo">017</atom>
    <atom name="ObjPartNoSum">019</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Astronomy;:;Astronomie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Research;:;Recherche</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Parts &amp; accessories;:;Pi&#232;ces et accessoires</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Unknown;:;Inconnu</atom>
      <atom name="NamOrganisationAcronym">Unknown</atom>
      <atom name="AddPhysCountry">Unknown</atom>
    </tuple>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Diameter;:;diam&#232;tre</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
    </table>
    <atom name="ArtDetMissing">Appears complete</atom>
    <atom name="ArtDetFinish">Gold coloured</atom>
    <atom name="NotNotes">Number breakdown: .1 camera; .2 lens cap; .3-.12 film holders; .14-.15 cylindrical brass bars; .16-.18 screws; .19 box with attached lid (two pieces broken from lid and marked as parts)</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2421</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">000.9</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">003.9</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">Metal, possibly brass</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
    </table>
    <table name="ArtCompMaterialCHINSpecific_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">brass - possible;:;laiton - possible</atom>
      </tuple>
    </table>
    <atom name="ConConditionStatus">Good;:;Bonne</atom>
    <atom name="ConDateChecked">2011-03-09</atom>
    <atom name="SrcLotAcquisition">yes;:;oui</atom>
  </tuple>
  <!-- Row 7 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1980.0425</atom>
    <atom name="ObjObjectName">Camera part/DE;:;Pi&#232;ce d'appareil-photo/DE</atom>
    <atom name="ObjPartNo">002</atom>
    <atom name="ObjPartNoSum">003</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Astronomy;:;Astronomie</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexGroup">Photography;:;Photographie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Deaccessioned;:;D&#233;classement</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexCategory">Deaccessioned;:;D&#233;classement</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>