<!DOCTYPE table [
<!ELEMENT table (tuple)*>
<!ATTLIST table name CDATA #REQUIRED>
<!ELEMENT tuple (table | tuple | atom)*>
<!ATTLIST tuple name CDATA #IMPLIED>
<!ELEMENT atom (#PCDATA)*>
<!ATTLIST atom name CDATA #REQUIRED>
<!ATTLIST atom type CDATA "text">
<!ATTLIST atom size CDATA "short">
]>
<?schema table           ecatalogue
    text short      ObjObjectDiscipline
    text short      ObjCatalogueNumber
    text long       ObjObjectName
    text long       ObjObjectType
    table           ObjModel_tab
      text long       ObjModel
    end
    text short      ObjSerialNumber
    text long       ObjObjectAKA
    text long       ObjModelUserName
    text short      ObjPartNo
    integer         ObjPartNoSum
    table           ArtLexRank_tab
      integer         ArtLexRank
    end
    table           ArtLexGroup_tab
      text short      ArtLexGroup
    end
    table           ArtLexCategory_tab
      text short      ArtLexCategory
    end
    table           ArtLexSubCategory_tab
      text short      ArtLexSubCategory
    end
    text short      ObjManufactureDate
    integer         ObjManufactureDateFrom
    integer         ObjManufactureDateTo
    tuple           ObjManufacturerRef
      text short      NamOrganisation
      text short      NamOrganisationAcronym
      text short      AddPhysCity
      text short      AddPhysCountry
      text short      AddPhysState
    end
    tuple           ObjDistributorRef
      text short      NamOrganisation
      text short      NamOrganisationAcronym
      text short      AddPhysCity
      text short      AddPhysCountry
      text short      AddPhysState
      text long       AddPhysStreet
    end
    text long       ArtConCanada
    text long       ArtConFunction
    text long       ArtConTechnical
    text long       ArtConPeriod
    text long       ArtConCountry
    text long       ArtConProvinceState
    text long       ArtConAreaNotes
    table           ArtCompWandDMeasurement_tab
      text short      ArtCompWandDMeasurement
    end
    table           MulMultiMediaRef_tab
      table           DocIdentifier_tab
        text short      DocIdentifier
      end
    end
    text long       ArtDetMissing
    text long       ArtDetFinish
    text long       ArtDetDecoration
    text long       CstmcNotWeb
    text long       CstmcNotExhibit
    text long       NotNotes
    text short      ArtRefWorksheet
    text short      ArtRefCollection
    text short      ArtRefManual
    table           ArtRefPatents_tab
      text long       ArtRefPatents
    end
    text short      ArtRefSuppInfo
    text short      ArtRefOversized
    text short      ArtRefManual
    text short      ArtRefStillImages
    text short      ArtRefNumberRange
    text short      ArtRefArticleNumber
    text short      ArtRefMultimedia
    text short      ArtRefExternalDoc
    table           ArtRefImage_tab
      text short      ArtRefImage
    end
    table           ArtRefReferences_tab
      text long       ArtRefReferences
    end
    tuple           LocCurrentLocationRef
      text short      LocLevel1
    end
    text short      LocIndependentlyMoveable
    date            AssAssessmentDate
    text short      AssConditionReport
    text long       AssOilCoolantEtc
    text long       AssActionRequired
    text long       AssActionTaken
    text short      AssOperable
    text short      AssRestored
    text long       AssHazards
    table           ArtCompWandDValue_tab
      text long       ArtCompWandDValue
    end
    table           ArtCompWandDUnit_tab
      text short      ArtCompWandDUnit
    end
    text long       ArtCompGeneralDescription
    table           ArtCompMaterialCHINGeneral_tab
      text long       ArtCompMaterialCHINGeneral
    end
    table           ArtCompMaterialCHINSpecific_tab
      text long       ArtCompMaterialCHINSpecific
    end
    text short      ConConditionStatus
    date            ConDateChecked
    text long       ConConditionDetails
    text long       ConHandlingInstructions
    text short      CstmcAdmAcquisitionProposal
    table           InfStatus_tab
      text short      InfStatus
    end
    table           InfComments0
      text long       InfComments
    end
    table           InfInspectionDate0
      date            InfInspectionDate
    end
    table           StaStable_tab
      text short      StaStable
    end
    table           StaInspectionDate0
      date            StaInspectionDate
    end
    table           StaComments0
      text long       StaComments
    end
    text short      SrcCulturalProperty
    text short      SrcLotAcquisition
    text long       SrcOtherNos
    text short      SrcPreviousCstmcNos
  end
?>
<!-- Data -->
<table name="ecatalogue">
  <!-- Row 1 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/B</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">002</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2475</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
    <atom name="SrcCulturalProperty">no;:;non</atom>
  </tuple>
  <!-- Row 2 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/C</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">003</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 3 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/D</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">004</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 4 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/E</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">005</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 5 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/F</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">006</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 6 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/G</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">007</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 7 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/H</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">008</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 8 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/I</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">009</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 9 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/J</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">010</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 10 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/K</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">011</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 11 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/L</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">012</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 12 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/M</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">013</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 13 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/Q</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">014</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 14 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/R</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">015</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 15 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/S</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">016</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 16 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/T</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">017</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Bookbinding;:;Reliure</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Lettering;:;Lettrage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Knights</atom>
      <atom name="NamOrganisationAcronym">Knights</atom>
      <atom name="AddPhysCity">London</atom>
      <atom name="AddPhysCountry">England</atom>
    </tuple>
    <atom name="ArtDetMissing">

From CA of 10/21/1994 by Tony Missio: Yes - Incomplete set of letters, 13 w/o handles.</atom>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
  </tuple>
  <!-- Row 17 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1978.0222</atom>
    <atom name="ObjObjectName">Handle letter;:;Outil de lettrage sur cuir</atom>
    <atom name="ObjObjectType">4pt/upper case</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Roman/U</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">018</atom>
    <atom name="ObjPartNoSum">024</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>