<!DOCTYPE table [
<!ELEMENT table (tuple)*>
<!ATTLIST table name CDATA #REQUIRED>
<!ELEMENT tuple (table | tuple | atom)*>
<!ATTLIST tuple name CDATA #IMPLIED>
<!ELEMENT atom (#PCDATA)*>
<!ATTLIST atom name CDATA #REQUIRED>
<!ATTLIST atom type CDATA "text">
<!ATTLIST atom size CDATA "short">
]>
<?schema table           ecatalogue
    text short      ObjObjectDiscipline
    text short      ObjCatalogueNumber
    text long       ObjObjectName
    text long       ObjObjectType
    table           ObjModel_tab
      text long       ObjModel
    end
    text short      ObjSerialNumber
    text long       ObjObjectAKA
    text long       ObjModelUserName
    text short      ObjPartNo
    integer         ObjPartNoSum
    table           ArtLexRank_tab
      integer         ArtLexRank
    end
    table           ArtLexGroup_tab
      text short      ArtLexGroup
    end
    table           ArtLexCategory_tab
      text short      ArtLexCategory
    end
    table           ArtLexSubCategory_tab
      text short      ArtLexSubCategory
    end
    text short      ObjManufactureDate
    integer         ObjManufactureDateFrom
    integer         ObjManufactureDateTo
    tuple           ObjManufacturerRef
      text short      NamOrganisation
      text short      NamOrganisationAcronym
      text short      AddPhysCity
      text short      AddPhysCountry
      text short      AddPhysState
    end
    tuple           ObjDistributorRef
      text short      NamOrganisation
      text short      NamOrganisationAcronym
      text short      AddPhysCity
      text short      AddPhysCountry
      text short      AddPhysState
      text long       AddPhysStreet
    end
    text long       ArtConCanada
    text long       ArtConFunction
    text long       ArtConTechnical
    text long       ArtConPeriod
    text long       ArtConCountry
    text long       ArtConProvinceState
    text long       ArtConAreaNotes
    table           ArtCompWandDMeasurement_tab
      text short      ArtCompWandDMeasurement
    end
    table           MulMultiMediaRef_tab
      table           DocIdentifier_tab
        text short      DocIdentifier
      end
    end
    text long       ArtDetMissing
    text long       ArtDetFinish
    text long       ArtDetDecoration
    text long       CstmcNotWeb
    text long       CstmcNotExhibit
    text long       NotNotes
    text short      ArtRefWorksheet
    text short      ArtRefCollection
    text short      ArtRefManual
    table           ArtRefPatents_tab
      text long       ArtRefPatents
    end
    text short      ArtRefSuppInfo
    text short      ArtRefOversized
    text short      ArtRefManual
    text short      ArtRefStillImages
    text short      ArtRefNumberRange
    text short      ArtRefArticleNumber
    text short      ArtRefMultimedia
    text short      ArtRefExternalDoc
    table           ArtRefImage_tab
      text short      ArtRefImage
    end
    table           ArtRefReferences_tab
      text long       ArtRefReferences
    end
    tuple           LocCurrentLocationRef
      text short      LocLevel1
    end
    text short      LocIndependentlyMoveable
    date            AssAssessmentDate
    text short      AssConditionReport
    text long       AssOilCoolantEtc
    text long       AssActionRequired
    text long       AssActionTaken
    text short      AssOperable
    text short      AssRestored
    text long       AssHazards
    table           ArtCompWandDValue_tab
      text long       ArtCompWandDValue
    end
    table           ArtCompWandDUnit_tab
      text short      ArtCompWandDUnit
    end
    text long       ArtCompGeneralDescription
    table           ArtCompMaterialCHINGeneral_tab
      text long       ArtCompMaterialCHINGeneral
    end
    table           ArtCompMaterialCHINSpecific_tab
      text long       ArtCompMaterialCHINSpecific
    end
    text short      ConConditionStatus
    date            ConDateChecked
    text long       ConConditionDetails
    text long       ConHandlingInstructions
    text short      CstmcAdmAcquisitionProposal
    table           InfStatus_tab
      text short      InfStatus
    end
    table           InfComments0
      text long       InfComments
    end
    table           InfInspectionDate0
      date            InfInspectionDate
    end
    table           StaStable_tab
      text short      StaStable
    end
    table           StaInspectionDate0
      date            StaInspectionDate
    end
    table           StaComments0
      text long       StaComments
    end
    text short      SrcCulturalProperty
    text short      SrcLotAcquisition
    text long       SrcOtherNos
    text short      SrcPreviousCstmcNos
  end
?>
<!-- Data -->
<table name="ecatalogue">
  <!-- Row 1 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">2000.0072</atom>
    <atom name="ObjObjectName">Pin, lapel;:;&#201;pinglette</atom>
    <atom name="ObjObjectType">Promotional</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">Superior</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">002</atom>
    <atom name="ObjPartNoSum">005</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Fire Fighting;:;Lutte contre les incendies</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Miscellaneous;:;Divers</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2000.0072.002.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2000.0072.002.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2421</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
    <atom name="SrcCulturalProperty">no;:;non</atom>
  </tuple>
  <!-- Row 2 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1971.0445</atom>
    <atom name="ObjObjectName">Box, alarm;:;Avertisseur</atom>
    <atom name="ObjObjectType">Electric/Exterior</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">cottage style</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">001</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Fire Fighting;:;Lutte contre les incendies</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Alarms;:;Alarmes</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">American Fire Alarm Telegraph</atom>
      <atom name="NamOrganisationAcronym">American Fire</atom>
    </tuple>
    <atom name="ArtConCanada">Type of device which started to be used in urban Canada at the time, to alert firefighters in a fire department, of the presence of a fire in the neighbourhood where the alarm box was situated. Must have come from one of Canada's major cities.</atom>
    <atom name="ArtConFunction">To rapidly transmit an alarm of fire to a firefighting force.</atom>
    <atom name="ArtConTechnical">Replaced the use of bells and the human voice (shouting) to alert firemen about the existence of fires all while divulging their location.

The first practical fire alarm system was developed in Boston in 1852, by Dr. William Channing and Moses Farmer. It worked on the principal of telegraphy: a signal was sent long distances over wires, by electric transmission. "In the first boxes, a notched code wheel was turned by a crank handle in the front of the box. Then, it evolved with a spring-driven, clockwork-type mechanism which drove the code wheel when activated by a lever."  Boxes were put on a pedestal or telephone pole at a street corner. Early boxes were locked with keys which were given to the citizens and policemen who had the responsibility of pulling the lever in the event of a fire. In 1875 a model was made that did not need a key.  In 1922, the quick-action door was put on the market.

There are two main components that make up this kind of fire alarm system: the telegraph mechanism, located on a street corner, and the alarm apparatus (gongs and indicators), located inside a fire department's Headquarters.  One-way communication between the telegraph and alarm system was made possible by linking both boxes with aerial and/or ground-level wires. Central station equipment would receive the signal, revealing the location of the fire, and would proceed to notify the firehouse nearest to the fire by transmitting another signal to their alarm box.</atom>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1971.0445.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1971.0445.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetFinish">Red, gable roof type/ Screws in 3 corners of pediment support pipes at top and bottom.  Top one is threaded inside.</atom>
    <atom name="NotNotes">The box is emptied of its inner box with the mechanism. The inner case could probably well be 1971.0446. (same provenance, technology of the period) The key is present. The mechanism most probably consisted of a bell magnet, signalling key, two line switches, a lightning arrester, a shunt switch.

The first practical fire alarm system was developed in 1852 in Boston, by Dr. William Channing and Moses Farmer. John Nelson Gamewell bought total rights of their invention in 1859. The patents were seized by the U.S. Government after the Civil War and were auctioned. The new owner formed a partnership with Gamewell to become Kennard and Company. In 1879, the Gamewell Fire Alarm Telegraph Company was formed with John N. Nelson as the proprietor. The trademark of the fist holding lightning bolts was registered. By 1910, Gamewell was holding 95% of the market share in USA and was also important in Canada. Gamewell dominated the market.

The Northern Electric Company Ltd. began in 1914 and at some point in her history, began producing Gamewell fire alarm systems.</atom>
    <atom name="ArtRefSuppInfo">Yes;:;Oui</atom>
    <atom name="ArtRefNumberRange">710444-446</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <table name="ArtRefReferences_tab">
      <tuple>
        <atom name="ArtRefReferences">1) James G. Piatti et S. Frost Piatti, Firefighting Antiques &amp; Memorabilia.  </atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">2) Andrew G. Gurka, Hot Stuff ! Firefighting Collectibles, 1994.</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">3) Gamewell web site, http://www.gamewell-fci.com/history.html</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">4) http://www.firehallmuseum.org/fire_alarm_telegraph/firealrm.htm</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2475</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
    <atom name="AssOperable">No;:;Non</atom>
    <atom name="AssRestored">No;:;Non</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">056.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">039.5</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">019.0</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">Metal</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
    </table>
    <table name="ArtCompMaterialCHINSpecific_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">cast-iron - possible;:;fonte - possible</atom>
      </tuple>
    </table>
    <atom name="SrcCulturalProperty">no;:;non</atom>
  </tuple>
  <!-- Row 3 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1968.0006</atom>
    <atom name="ObjObjectName">Helmet;:;Casque de protection</atom>
    <atom name="ObjObjectType">FIREMAN'S/LEATHER</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">CNR - LEASIDE SHOPS</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">001</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Fire Fighting;:;Lutte contre les incendies</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexGroup">Motorized Ground Transportation;:;Transports terrestres motoris&#233;s</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Clothing &amp; personal safety apparatus;:;V&#234;tements et &#233;quipement de protection individuelle</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexCategory">Miscellaneous;:;Divers</atom>
      </tuple>
    </table>
    <atom name="ObjManufactureDate">after;:;apres</atom>
    <atom name="ObjManufactureDateFrom">1918</atom>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Cairns &amp; Bro.</atom>
      <atom name="NamOrganisationAcronym">Cairns</atom>
      <atom name="AddPhysCity">New York</atom>
      <atom name="AddPhysCountry">United States of America</atom>
      <atom name="AddPhysState">New York</atom>
    </tuple>
    <atom name="ArtConCanada">EXAMPLE OF EQUIPMENT USED BY WORKERS FOR THE CANADIAN NATIONAL RAILWAY SHOPS IN LEASIDE ONTARIO</atom>
    <atom name="ArtConFunction">USED TO PROTECT THE WEARER FROM INJURY</atom>
    <atom name="ArtConPeriod">SOME TIME AFTER 1918 WHEN THE CNR WAS ESTABLISHED</atom>
    <atom name="ArtConCountry">Canada</atom>
    <atom name="ArtConProvinceState">Ontario</atom>
    <atom name="ArtConAreaNotes">LEASIDE ONTARIO</atom>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1968.0006.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1968.0006.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetMissing">None: appears complete.</atom>
    <atom name="ArtDetFinish">PAINTED GLOSS BLACK; WHITE LETTERS ON FRONT MOUNTED ON RED</atom>
    <atom name="ArtDetDecoration">DOG LIKE CARVING ON TOP OF HAT ATTACHED TO FRONT SHIELD/ SCROLLS MOLDED INTO BRIM/ EIGHT RIDGES AROUND TOP OF HAT</atom>
    <atom name="ArtRefCollection">CN</atom>
    <atom name="ArtRefSuppInfo">Yes;:;Oui</atom>
    <atom name="ArtRefArticleNumber">6420-137</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Colour negative;:;N&#233;gatif en couleur</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2475</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssAssessmentDate">2013-06-04</atom>
    <atom name="AssConditionReport">Yes;:;Oui</atom>
    <atom name="AssOilCoolantEtc">no</atom>
    <atom name="AssOperable">Yes;:;Oui</atom>
    <atom name="AssRestored">No;:;Non</atom>
    <atom name="AssHazards">no</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">035.7</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">027.6</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">024.4</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">LEATHER; FELT LINING; METAL HARDWARE</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">skin;:;peau</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">fibre;:;fibre</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
    </table>
    <table name="ArtCompMaterialCHINSpecific_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">leather;:;cuir</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">felt;:;feutre</atom>
      </tuple>
    </table>
    <table name="InfStatus_tab">
      <tuple>
        <atom name="InfStatus">No;:;Non</atom>
      </tuple>
    </table>
    <table name="InfInspectionDate0">
      <tuple>
        <atom name="InfInspectionDate">2013-06-04</atom>
      </tuple>
    </table>
    <table name="StaStable_tab">
      <tuple>
        <atom name="StaStable">Yes;:;Oui</atom>
      </tuple>
    </table>
    <table name="StaInspectionDate0">
      <tuple>
        <atom name="StaInspectionDate">2013-06-04</atom>
      </tuple>
    </table>
    <atom name="SrcOtherNos">CN-135</atom>
  </tuple>
  <!-- Row 4 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1976.0534</atom>
    <atom name="ObjObjectName">Wagon, hose;:;Voiture pour tuyau d'incendie</atom>
    <atom name="ObjObjectType">TWO-WHEEL/HAND-DRAWN</atom>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">001</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Fire Fighting;:;Lutte contre les incendies</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Accessory equipment;:;&#201;quipement auxiliaire</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Unknown;:;Inconnu</atom>
      <atom name="NamOrganisationAcronym">Unknown</atom>
      <atom name="AddPhysCountry">Unknown</atom>
    </tuple>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1976.0534.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1976.0534.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetMissing">none apparent</atom>
    <atom name="ArtDetFinish">RED PAINT</atom>
    <atom name="ArtDetDecoration">BOLD BLACK LINE DESIGN USED ON SPOKES &amp; EDGES OF METAL FRAME/ FINE WHITE LINE DESIGN CONTAINED BY BLACK</atom>
    <atom name="ArtRefSuppInfo">No;:;Non</atom>
    <atom name="ArtRefNumberRange">1976.0534-1976.0535</atom>
    <atom name="ArtRefArticleNumber">6383-09</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <table name="ArtRefReferences_tab">
      <tuple>
        <atom name="ArtRefReferences">Museum Documents in Supp. Info.</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">1867</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssAssessmentDate">2005-05-27</atom>
    <atom name="AssConditionReport">Yes;:;Oui</atom>
    <atom name="AssOilCoolantEtc">none</atom>
    <atom name="AssActionRequired">treated previously</atom>
    <atom name="AssOperable">Yes;:;Oui</atom>
    <atom name="AssRestored">No;:;Non</atom>
    <atom name="AssHazards">none</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">223.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">160.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">140.0</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">WOOD (WHEELS, TUBS)/ IRON (FORGES &amp; CAST) REEL, WHEEL RIMS, HANDLE, FRAME, ETC./ CANVAS HOSE</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">wood;:;bois</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">fibre;:;fibre</atom>
      </tuple>
    </table>
    <table name="ArtCompMaterialCHINSpecific_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">iron;:;fer</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">canvas;:;toile</atom>
      </tuple>
    </table>
    <table name="InfStatus_tab">
      <tuple>
        <atom name="InfStatus">No;:;Non</atom>
      </tuple>
    </table>
    <table name="InfInspectionDate0">
      <tuple>
        <atom name="InfInspectionDate">2005-05-27</atom>
      </tuple>
    </table>
    <table name="StaStable_tab">
      <tuple>
        <atom name="StaStable">Yes;:;Oui</atom>
      </tuple>
    </table>
    <table name="StaInspectionDate0">
      <tuple>
        <atom name="StaInspectionDate">2005-05-27</atom>
      </tuple>
    </table>
    <table name="StaComments0">
      <tuple>
        <atom name="StaComments">treated in 2004,  to stabilise corrosion and consolidate paint.</atom>
      </tuple>
    </table>
  </tuple>
  <!-- Row 5 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1996.0551</atom>
    <atom name="ObjObjectName">Mounting, extinguisher;:;Support d'extincteur</atom>
    <atom name="ObjObjectType">WALL &amp; CEILING</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">GXA/GXAS</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">011</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Fire Fighting;:;Lutte contre les incendies</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Extinguishers;:;Extincteurs</atom>
      </tuple>
    </table>
    <atom name="ObjManufactureDate">circa;:;vers</atom>
    <atom name="ObjManufactureDateFrom">1942</atom>
    <atom name="ObjManufactureDateTo">1955</atom>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">ELECTRICAL MFG. CO.</atom>
      <atom name="NamOrganisationAcronym">ELECTRICAL</atom>
      <atom name="AddPhysCity">Montmagny</atom>
      <atom name="AddPhysCountry">Canada</atom>
      <atom name="AddPhysState">Qu&#233;bec</atom>
    </tuple>
    <tuple name="ObjDistributorRef">
      <atom name="NamOrganisation">GUARD-X INC.</atom>
      <atom name="NamOrganisationAcronym">GUARD X</atom>
    </tuple>
    <atom name="ArtConCanada">SYSTEM WAS DEVELOPED AND PATENTED BY GUARD-X OF MONTREAL. GUARD-X WAS ESTABLISHED IN 1942. IT MANUFACTURED &amp; SOLD THE CARBONTETRACHOLORIDE GRENADE SYSTEM OF FIRE EXTINGUISHERS FOR MAINLY INDUSTRIAL USE IN EASTERN CANADA UNTIL THE SYSTEM WAS DECLARED DANGEROUS AND BANNED IN CANADA IN THE 1950S.</atom>
    <atom name="ArtConFunction">USED, WHEN AFFIXED TO A WALL OR CEILING, TO HOLD A GLASS GRENADE FILLED WITH CHEMICALS FOR FIRE EXTINGUISHING, AND TO BREAK THE GLASS WHEN HEAT FROM A FIRE CAUSES A FUSIBLE LINK TO MELT. ALSO A CARTRIDGE DISCHARGES TO GIVE AN ALARM WHEN THE HAMMER BREAKS THE GLASS.</atom>
    <atom name="ArtConTechnical">THE GUARD-X SYSTEM OFFERED THE GREAT ADVANTAGE OF BEING 'AUTOMATIC'. THE MOUNTING HAS A FUSIBLE METAL LINK THAT MELTS AT A 'PRESET' TEMP RELEASING A HAMMER ATTACHED TO A SPRING TO SMASH A GLASS GRENADE WHICH RELEASES CHEMICALS TO SUPPRESS A FIRE WITHIN 800 CU FT. OF THE EXTINGUISHER. IT ALSO COULD BE WIRED TO A BELL.</atom>
    <atom name="ArtConPeriod">THIS SET USED IN ONE HOUSE IN OTTAWA (71 ORIN ST.) FROM THE 1940S UP TO 1996 WHEN IT WAS REMOVED</atom>
    <atom name="ArtConCountry">Canada</atom>
    <atom name="ArtConProvinceState">Ontario</atom>
    <atom name="ArtConAreaNotes">THIS SET USED IN OTTAWA BUT WOULD HAVE BEEN AVAILABLE FOR USE THROUGHOUT EASTERN CANADA</atom>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1996.0551.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1996.0551.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetMissing">APPEARS COMPLETE</atom>
    <atom name="ArtDetFinish">PAINTED SILVER GLOSS/ DECAL GOLD BACKGROUND WITH RED BORDER AND BLACK PRINTING</atom>
    <atom name="NotNotes">NO. BREAKDOWN: .1-.5 IDENTICAL CEILING MOUNTS; .6-.11 IDENTICAL WALL MOUNTS. PTS: WIRING &amp; MOUNTING HARDWARE/ *MFR: MFD FOR GUARD-X, FOR ATTACHING THEIR PATENTED SYSTEM FOR HOLDING &amp; BREAKING THE CARBONTET GRENADES/ *DIM: GIVEN ARE FOR .1-.5; .6-.11 L-25.5 W-11 H-14 CM/ THESE MOUNTS WOULD HAVE HELD THE GRENADES 960552.1-.11; &amp; WOULD HAVE BEEN WIRED TO THE ELECTRICAL BOX 960553 WHICH ALLOWED FOR THE RINGING OF THE FIRE BELL 960554/ EACH CONTAINED AN EXPLODING DEVICE, NOW DEACTIVATED (SEE CONSERVATION REPORT</atom>
    <table name="ArtRefPatents_tab">
      <tuple>
        <atom name="ArtRefPatents">CAN. 398,190</atom>
      </tuple>
    </table>
    <atom name="ArtRefSuppInfo">Yes;:;Oui</atom>
    <atom name="ArtRefNumberRange">1996.0551-.0554</atom>