<!DOCTYPE table [
<!ELEMENT table (tuple)*>
<!ATTLIST table name CDATA #REQUIRED>
<!ELEMENT tuple (table | tuple | atom)*>
<!ATTLIST tuple name CDATA #IMPLIED>
<!ELEMENT atom (#PCDATA)*>
<!ATTLIST atom name CDATA #REQUIRED>
<!ATTLIST atom type CDATA "text">
<!ATTLIST atom size CDATA "short">
]>
<?schema table           ecatalogue
    text short      ObjObjectDiscipline
    text short      ObjCatalogueNumber
    text long       ObjObjectName
    text long       ObjObjectType
    table           ObjModel_tab
      text long       ObjModel
    end
    text short      ObjSerialNumber
    text long       ObjObjectAKA
    text long       ObjModelUserName
    text short      ObjPartNo
    integer         ObjPartNoSum
    table           ArtLexRank_tab
      integer         ArtLexRank
    end
    table           ArtLexGroup_tab
      text short      ArtLexGroup
    end
    table           ArtLexCategory_tab
      text short      ArtLexCategory
    end
    table           ArtLexSubCategory_tab
      text short      ArtLexSubCategory
    end
    text short      ObjManufactureDate
    integer         ObjManufactureDateFrom
    integer         ObjManufactureDateTo
    tuple           ObjManufacturerRef
      text short      NamOrganisation
      text short      NamOrganisationAcronym
      text short      AddPhysCity
      text short      AddPhysCountry
      text short      AddPhysState
    end
    tuple           ObjDistributorRef
      text short      NamOrganisation
      text short      NamOrganisationAcronym
      text short      AddPhysCity
      text short      AddPhysCountry
      text short      AddPhysState
      text long       AddPhysStreet
    end
    text long       ArtConCanada
    text long       ArtConFunction
    text long       ArtConTechnical
    text long       ArtConPeriod
    text long       ArtConCountry
    text long       ArtConProvinceState
    text long       ArtConAreaNotes
    table           ArtCompWandDMeasurement_tab
      text short      ArtCompWandDMeasurement
    end
    table           MulMultiMediaRef_tab
      table           DocIdentifier_tab
        text short      DocIdentifier
      end
    end
    text long       ArtDetMissing
    text long       ArtDetFinish
    text long       ArtDetDecoration
    text long       CstmcNotWeb
    text long       CstmcNotExhibit
    text long       NotNotes
    text short      ArtRefWorksheet
    text short      ArtRefCollection
    text short      ArtRefManual
    table           ArtRefPatents_tab
      text long       ArtRefPatents
    end
    text short      ArtRefSuppInfo
    text short      ArtRefOversized
    text short      ArtRefManual
    text short      ArtRefStillImages
    text short      ArtRefNumberRange
    text short      ArtRefArticleNumber
    text short      ArtRefMultimedia
    text short      ArtRefExternalDoc
    table           ArtRefImage_tab
      text short      ArtRefImage
    end
    table           ArtRefReferences_tab
      text long       ArtRefReferences
    end
    tuple           LocCurrentLocationRef
      text short      LocLevel1
    end
    text short      LocIndependentlyMoveable
    date            AssAssessmentDate
    text short      AssConditionReport
    text long       AssOilCoolantEtc
    text long       AssActionRequired
    text long       AssActionTaken
    text short      AssOperable
    text short      AssRestored
    text long       AssHazards
    table           ArtCompWandDValue_tab
      text long       ArtCompWandDValue
    end
    table           ArtCompWandDUnit_tab
      text short      ArtCompWandDUnit
    end
    text long       ArtCompGeneralDescription
    table           ArtCompMaterialCHINGeneral_tab
      text long       ArtCompMaterialCHINGeneral
    end
    table           ArtCompMaterialCHINSpecific_tab
      text long       ArtCompMaterialCHINSpecific
    end
    text short      ConConditionStatus
    date            ConDateChecked
    text long       ConConditionDetails
    text long       ConHandlingInstructions
    text short      CstmcAdmAcquisitionProposal
    table           InfStatus_tab
      text short      InfStatus
    end
    table           InfComments0
      text long       InfComments
    end
    table           InfInspectionDate0
      date            InfInspectionDate
    end
    table           StaStable_tab
      text short      StaStable
    end
    table           StaInspectionDate0
      date            StaInspectionDate
    end
    table           StaComments0
      text long       StaComments
    end
    text short      SrcCulturalProperty
    text short      SrcLotAcquisition
    text long       SrcOtherNos
    text short      SrcPreviousCstmcNos
  end
?>
<!-- Data -->
<table name="ecatalogue">
  <!-- Row 1 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1966.0224</atom>
    <atom name="ObjObjectName">Watch, pocket;:;Montre de poche</atom>
    <atom name="ObjObjectType">17 JEWELS/EXPOSED WORKS</atom>
    <atom name="ObjSerialNumber">06431I</atom>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">001</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Horology;:;Horlogerie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Watches;:;Montres</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Pocket;:;Poche</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Unknown;:;Inconnu</atom>
      <atom name="NamOrganisationAcronym">Unknown</atom>
      <atom name="AddPhysCountry">Unknown</atom>
    </tuple>
    <atom name="ArtConFunction">SPECIALLY MADE WITH NO DIAL FACE AND A GLASS BACK SO THAT THE WORKS CAN BE SEEN FROM BOTH SIDES.</atom>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1966.0224.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1966.0224.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetMissing">FACE ON FRONT REMOVED AND BACK REPLACED BY GLASS TO       DISPLAY WORKS.</atom>
    <atom name="ArtDetFinish">POLISHED GOLD CASE/ BLACK HOUR AND MINUTE HANDS.</atom>
    <atom name="NotNotes">SOURCE: PROBABLY ACQUIRED FROM BIRKS FOR NMST EXHIBITION</atom>
    <atom name="ArtRefSuppInfo">No;:;Non</atom>
    <atom name="ArtRefNumberRange">660223-660224</atom>
    <atom name="ArtRefArticleNumber">MISSING</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Black &amp; white negative;:;N&#233;gatif noir et blanc</atom>
      </tuple>
    </table>
    <table name="ArtRefReferences_tab">
      <tuple>
        <atom name="ArtRefReferences">SEE 660223 S.I. FOR CONSERVATION REPORT</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2475</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">Yes;:;Oui</atom>
    <atom name="AssOperable">Yes;:;Oui</atom>
    <atom name="AssRestored">No;:;Non</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">005.8</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">004.6</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">001.0</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">GOLD/ STEEL/ GLASS</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">glass;:;verre</atom>
      </tuple>
    </table>
    <table name="ArtCompMaterialCHINSpecific_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">gold;:;or</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">steel;:;acier</atom>
      </tuple>
    </table>
    <atom name="SrcCulturalProperty">no;:;non</atom>
    <atom name="SrcPreviousCstmcNos">DS0178</atom>
  </tuple>
  <!-- Row 2 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1966.0223</atom>
    <atom name="ObjObjectName">Watch, pocket;:;Montre de poche</atom>
    <atom name="ObjObjectType">17 JEWELS/EXPOSED WORKS</atom>
    <atom name="ObjSerialNumber">06432I</atom>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">001</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Horology;:;Horlogerie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Watches;:;Montres</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Pocket;:;Poche</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Unknown;:;Inconnu</atom>
      <atom name="NamOrganisationAcronym">Unknown</atom>
      <atom name="AddPhysCountry">Unknown</atom>
    </tuple>
    <atom name="ArtConFunction">SPECIALLY MADE WITH NO DIAL FACE AND A GLASS BACK SO THAT THE WORKS CAN BE SEEN FROM BOTH SIDES.</atom>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1966.0223.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1966.0223.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetMissing">FACE ON FRONT REMOVED AND BACK REPLACED BY GLASS TO       DISPLAY WORKS.</atom>
    <atom name="ArtDetFinish">POLISHED GOLD CASE/ BLACK HOUR AND MINUTE HANDS.</atom>
    <atom name="NotNotes">SOURCE: PROBABLY ACQUIRED FROM BIRKS FOR NMST EXHIBITION</atom>
    <atom name="ArtRefSuppInfo">Yes;:;Oui</atom>
    <atom name="ArtRefNumberRange">660223-660224</atom>
    <atom name="ArtRefArticleNumber">MISSING</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Black &amp; white negative;:;N&#233;gatif noir et blanc</atom>
      </tuple>
    </table>
    <table name="ArtRefReferences_tab">
      <tuple>
        <atom name="ArtRefReferences">See Museum Documentation in Supp. Info.</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2475</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">Yes;:;Oui</atom>
    <atom name="AssOperable">Yes;:;Oui</atom>
    <atom name="AssRestored">No;:;Non</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">005.8</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">004.6</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">001.0</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">GOLD/ STEEL/ GLASS</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">glass;:;verre</atom>
      </tuple>
    </table>
    <table name="ArtCompMaterialCHINSpecific_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">gold;:;or</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">steel;:;acier</atom>
      </tuple>
    </table>
    <atom name="SrcCulturalProperty">no;:;non</atom>
    <atom name="SrcPreviousCstmcNos">DS0177</atom>
  </tuple>
  <!-- Row 3 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1989.0398</atom>
    <atom name="ObjObjectName">Clock;:;Horloge</atom>
    <atom name="ObjObjectType">WALL/SPRING DRIVEN/HANDS/PENDULUM</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">VIENNA REGULATOR</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">004</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Horology;:;Horlogerie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Clocks;:;Horloges</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Domestic;:;Domestique</atom>
      </tuple>
    </table>
    <atom name="ObjManufactureDate">between;:;entre</atom>
    <atom name="ObjManufactureDateFrom">1870</atom>
    <atom name="ObjManufactureDateTo">1895</atom>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Unknown;:;Inconnu</atom>
      <atom name="NamOrganisationAcronym">Unknown</atom>
      <atom name="AddPhysCountry">Austria</atom>
    </tuple>
    <atom name="ArtConFunction">USED TO TELL TIME OF DAY IN HOURS, MINUTES AND SECONDS IN A DOMESTIC SETTING</atom>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1989.0398.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1989.0398.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetFinish">CASE STAINED &amp; VARNISHED/ BRASS LACQUERED; CREAM COLOURED CLOCK FACE WITH BLACK ROMAN NUMERALS/ BLACK PAINTED PENDULUM ARM</atom>
    <atom name="ArtDetDecoration">FACE: RED STYLIZED FLEUR-DE-LYS BETWEEN EACH NUMBER/ FINIALS ON TOP &amp; BOTTOM OF CASE/ CARVED PILLARS ON EACH SIDE OF FRONT WINDOW/ EMBOSSED FLOWER ON CROWN PIECE</atom>
    <atom name="NotNotes">NO. BREAKDOWN: .1 CLOCK; .2 PENDULUM; .3-.4 WEIGHTS. PTS: TOP DECORATIVE CAP (REMOVED)/ TYPE: ALTDEUTSCH STYLE/ DATE RCVD: UNKNOWN; DATE GIVEN IS WHEN CLOCK WAS REMOVED FROM DISPLAY &amp; RCVD IN STORAGE/</atom>
    <atom name="ArtRefSuppInfo">Yes;:;Oui</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Black &amp; white negative;:;N&#233;gatif noir et blanc</atom>
      </tuple>
    </table>
    <table name="ArtRefReferences_tab">
      <tuple>
        <atom name="ArtRefReferences">Museum Documents, Additional Material in Supp. Info.</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2475</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssConditionReport">Yes;:;Oui</atom>
    <atom name="AssOperable">No;:;Non</atom>
    <atom name="AssRestored">No;:;Non</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">049.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">020.5</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">132.0</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">WOODEN CASE WITH METAL HARDWARE/ PORCELAIN CLOCK FACE/ BRASS WEIGHTS, PENDULUM, WORKING PARTS/ GLASS WINDOWS ON CASE/ WOODEN PENDULUM ARM</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">wood;:;bois</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">ceramic;:;c&#233;ramique</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">glass;:;verre</atom>
      </tuple>
    </table>
    <table name="ArtCompMaterialCHINSpecific_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">brass;:;laiton</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">porcelain;:;porcelaine</atom>
      </tuple>
    </table>
  </tuple>
  <!-- Row 4 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">2013.0027</atom>
    <atom name="ObjObjectName">Box, watch</atom>
    <atom name="ObjPartNo">005</atom>
    <atom name="ObjPartNoSum">008</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Horology;:;Horlogerie</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexGroup">Exploration and Survey;:;Exploration et lev&#233;</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Watches;:;Montres</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexCategory">Measurement-position;:;Mesure-position</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Wrist;:;Poignet</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexSubCategory">Longitude-latitude-elevation;:;Latitude-longitude-&#233;l&#233;vation</atom>
      </tuple>
    </table>
    <atom name="ObjManufactureDate">circa;:;vers</atom>
    <atom name="ObjManufactureDateFrom">2012</atom>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Unknown;:;Inconnu</atom>
      <atom name="NamOrganisationAcronym">Unknown</atom>
      <atom name="AddPhysCountry">Unknown</atom>
    </tuple>
    <atom name="ArtConCanada">In response to the corporate priority of collecting new technologies, the Collection and Research Branch identified in December 2012 (A. Adamek acquisition proposal Dec. 2012) the theme of consumer culture as an area of focus - therefore, collecting consumer culture new technology devices to which this GPS watch belongs to. This watch was collected for its technical innovation, research collection, and because it is representative of type. This GPS watch would appeal to people involved in sports, adventure, travel, and the outdoors. In several magazines, (Outside, Outdoors, Backpacker) the Suunto Ambit consistently ranked as &#147;must have gear&#148; for the outdoor enthusiast. It currently is one of the more common consumer choices for a variety of reasons: 1.Items proposed are often marketed to the public as improving the quality of life and therefore necessary. 2.They are associated with safety and health 3.They are promoted as fun, increasing the entertainment value rather than technological functionality 4.They are designed to make the user feel special either unique or part of a subculture 5.They facilitate instant communication and access to data.</atom>
    <atom name="ArtConFunction">The box to store the SUUNTO GPS Watch, Heart rate belt, USB cable, quick guides and covers.</atom>
    <atom name="ArtConTechnical">The Suunto Ambit GPS watch combines several instruments in one device such a barometer and barograph, altimeter, thermometer, chronograph, compass, global positioning system (GPS), heart rate monitor, as well as separate speed and cadence sensors for cyclists. [see Ref. # Worksheetl]</atom>
    <atom name="ArtConPeriod">2010+</atom>
    <atom name="ArtConCountry">Canada</atom>
    <atom name="ArtConProvinceState">British Columbia</atom>
    <atom name="ArtConAreaNotes">This watch was used ski mountaineering April 19 &#150; 28, 2013 in the Columbia-Sushwap District outside the Northern boundary of Glacier National Park, British Columbia to track elevation gain, distance travelled, total vertical climbed, speed, and GPS track in the areas near Perfect and Nordic glaciers up to an elevation of 9,400&#146;. The watch was also used to record a walking tour of the Canada Science and Technology Museum Technology Park (observatory, Atlas rocket, radar, derrick, locomotive, lighthouse, and Shay locomotive storage facility at 2495). [see notes for further info.]</atom>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2013.0027.005.aa.cs.JPG</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2013.0027.005.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetMissing">Nothing is missing.</atom>
    <atom name="ArtDetFinish">Black cardboard box with a flip top and flip insert.</atom>
    <atom name="ArtDetDecoration">None.</atom>
    <atom name="NotNotes">No. Breakdown: .1 watch, wrist, .2. USB cable/charger, .3 belt, heart rate monitor,  .4 Monitor. heart rate, .5 box, .6 box sleeve,  .7 sleeve, .8 sleeve:
Note:  Canadian Context: First proposed by the U.S. Defense Department in 1973, the Navstar Global Positioning System took 20 years to build and bring into operation. Originally developed for military applications, today&#146;s GPS hand-held receivers are found in automobiles, marine navigation systems, pleasure craft, fish finders, cyclocomputers, cameras, security systems, smart phones, and wrist watches such as this one. A full suit of applications enables the user to upload GPS tracks of travels or the exact location a photo was taken to any number of websites enabled by Google Maps or Google Earth. &#147;The items proposed are reflective of culture that requires technologies to be instant, small and portable, simple to operate, entertaining, and beautiful. These features take priority to technological functions and their quality.&#148;  (A. Adamek, December 2012).
See:  Enterprise, Collection Development, Acquisitions-Collection Develpment, 2013, Suunto GPS for the User Manual, KML_GPS Track Files, GPX-GPS Track Files.</atom>
    <atom name="ArtRefWorksheet">Yes;:;Oui</atom>
    <atom name="ArtRefManual">Yes;:;Oui</atom>
    <atom name="ArtRefSuppInfo">Yes;:;Oui</atom>
    <atom name="ArtRefOversized">No;:;Non</atom>
    <atom name="ArtRefManual">Yes;:;Oui</atom>
    <atom name="ArtRefStillImages">No;:;Non</atom>
    <atom name="ArtRefMultimedia">No;:;Non</atom>
    <atom name="ArtRefExternalDoc">No;:;Non</atom>
    <table name="ArtRefReferences_tab">
      <tuple>
        <atom name="ArtRefReferences">Ref. # 1 Worksheet</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">Babaian, S.A., Setting the Course: A History of Marine Navigation in Canada, Canada Science and Technology Museum, Transformation Series 14, Ottawa, 2006.</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">Suunto Ambit 2.0 User Guide</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2421</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">12.5</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">9.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">9.4</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">Black cardboard box with a flip top and flip insert.</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">paper;:;papier</atom>
      </tuple>
    </table>
    <table name="ArtCompMaterialCHINSpecific_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">cardboard;:;carton</atom>
      </tuple>
    </table>
    <atom name="CstmcAdmAcquisitionProposal">No</atom>
  </tuple>
  <!-- Row 5 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">2013.0027</atom>
    <atom name="ObjObjectName">Sleeve, box</atom>
    <atom name="ObjPartNo">006</atom>
    <atom name="ObjPartNoSum">008</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Horology;:;Horlogerie</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexGroup">Exploration and Survey;:;Exploration et lev&#233;</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Watches;:;Montres</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexCategory">Measurement-position;:;Mesure-position</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Wrist;:;Poignet</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexSubCategory">Longitude-latitude-elevation;:;Latitude-longitude-&#233;l&#233;vation</atom>
      </tuple>
    </table>
    <atom name="ObjManufactureDate">circa;:;vers</atom>
    <atom name="ObjManufactureDateFrom">2012</atom>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Unknown;:;Inconnu</atom>
      <atom name="NamOrganisationAcronym">Unknown</atom>
      <atom name="AddPhysCountry">Unknown</atom>
    </tuple>