<!DOCTYPE table [
<!ELEMENT table (tuple)*>
<!ATTLIST table name CDATA #REQUIRED>
<!ELEMENT tuple (table | tuple | atom)*>
<!ATTLIST tuple name CDATA #IMPLIED>
<!ELEMENT atom (#PCDATA)*>
<!ATTLIST atom name CDATA #REQUIRED>
<!ATTLIST atom type CDATA "text">
<!ATTLIST atom size CDATA "short">
]>
<?schema table           ecatalogue
    text short      ObjObjectDiscipline
    text short      ObjCatalogueNumber
    text long       ObjObjectName
    text long       ObjObjectType
    table           ObjModel_tab
      text long       ObjModel
    end
    text short      ObjSerialNumber
    text long       ObjObjectAKA
    text long       ObjModelUserName
    text short      ObjPartNo
    integer         ObjPartNoSum
    table           ArtLexRank_tab
      integer         ArtLexRank
    end
    table           ArtLexGroup_tab
      text short      ArtLexGroup
    end
    table           ArtLexCategory_tab
      text short      ArtLexCategory
    end
    table           ArtLexSubCategory_tab
      text short      ArtLexSubCategory
    end
    text short      ObjManufactureDate
    integer         ObjManufactureDateFrom
    integer         ObjManufactureDateTo
    tuple           ObjManufacturerRef
      text short      NamOrganisation
      text short      NamOrganisationAcronym
      text short      AddPhysCity
      text short      AddPhysCountry
      text short      AddPhysState
    end
    tuple           ObjDistributorRef
      text short      NamOrganisation
      text short      NamOrganisationAcronym
      text short      AddPhysCity
      text short      AddPhysCountry
      text short      AddPhysState
      text long       AddPhysStreet
    end
    text long       ArtConCanada
    text long       ArtConFunction
    text long       ArtConTechnical
    text long       ArtConPeriod
    text long       ArtConCountry
    text long       ArtConProvinceState
    text long       ArtConAreaNotes
    table           ArtCompWandDMeasurement_tab
      text short      ArtCompWandDMeasurement
    end
    table           MulMultiMediaRef_tab
      table           DocIdentifier_tab
        text short      DocIdentifier
      end
    end
    text long       ArtDetMissing
    text long       ArtDetFinish
    text long       ArtDetDecoration
    text long       CstmcNotWeb
    text long       CstmcNotExhibit
    text long       NotNotes
    text short      ArtRefWorksheet
    text short      ArtRefCollection
    text short      ArtRefManual
    table           ArtRefPatents_tab
      text long       ArtRefPatents
    end
    text short      ArtRefSuppInfo
    text short      ArtRefOversized
    text short      ArtRefManual
    text short      ArtRefStillImages
    text short      ArtRefNumberRange
    text short      ArtRefArticleNumber
    text short      ArtRefMultimedia
    text short      ArtRefExternalDoc
    table           ArtRefImage_tab
      text short      ArtRefImage
    end
    table           ArtRefReferences_tab
      text long       ArtRefReferences
    end
    tuple           LocCurrentLocationRef
      text short      LocLevel1
    end
    text short      LocIndependentlyMoveable
    date            AssAssessmentDate
    text short      AssConditionReport
    text long       AssOilCoolantEtc
    text long       AssActionRequired
    text long       AssActionTaken
    text short      AssOperable
    text short      AssRestored
    text long       AssHazards
    table           ArtCompWandDValue_tab
      text long       ArtCompWandDValue
    end
    table           ArtCompWandDUnit_tab
      text short      ArtCompWandDUnit
    end
    text long       ArtCompGeneralDescription
    table           ArtCompMaterialCHINGeneral_tab
      text long       ArtCompMaterialCHINGeneral
    end
    table           ArtCompMaterialCHINSpecific_tab
      text long       ArtCompMaterialCHINSpecific
    end
    text short      ConConditionStatus
    date            ConDateChecked
    text long       ConConditionDetails
    text long       ConHandlingInstructions
    text short      CstmcAdmAcquisitionProposal
    table           InfStatus_tab
      text short      InfStatus
    end
    table           InfComments0
      text long       InfComments
    end
    table           InfInspectionDate0
      date            InfInspectionDate
    end
    table           StaStable_tab
      text short      StaStable
    end
    table           StaInspectionDate0
      date            StaInspectionDate
    end
    table           StaComments0
      text long       StaComments
    end
    text short      SrcCulturalProperty
    text short      SrcLotAcquisition
    text long       SrcOtherNos
    text short      SrcPreviousCstmcNos
  end
?>
<!-- Data -->
<table name="ecatalogue">
  <!-- Row 1 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">2010.0255</atom>
    <atom name="ObjObjectName">Coveralls;:;Bleus de travail</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">CANMET</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">001</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Mining and Metallurgy;:;Mines et m&#233;tallurgie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Personal gear;:;Outillage personnel</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Unknown;:;Inconnu</atom>
      <atom name="NamOrganisationAcronym">Unknown</atom>
      <atom name="AddPhysCountry">Canada</atom>
    </tuple>
    <atom name="ArtConCanada">The CANMET-MMSL EXPERIMENTAL MINE in Val-d'Or, Quebec, was established in 1991 in response to Canadian and local mining industry needs for an increased emphasis on applied research. The former Beacon Gold Mine is an underground facility for in-situ testing and research in a true mining environment. The Experimental Mine is also available for individual companies to test equipment or for training purposes on a contract basis. CANMET-MMSL scientists at the Experimental Mine also offer a range of services to the local mining industry. The equipment suggested for acquisition represents the testing done by CANMET scientists. 
The mine comprises a unique underground hard rock testing site with an access ramp and five underground levels. There are two interconnected gold mines at this site. The earlier mine, Le Roy was opened from 1931-1932. It was operated by Le Roy Gold Mines Ltd. The Beacon II was open in mid-1980s and was owned by Mines Aurizon Ltd. There are over 2500 metres of drifts, plus raises and secondary openings and shrinkage stopes. Val d&#146;Or area is very important to Canadian mining since gold was discovered there in 1923. Gold, copper, zinc and lead are still mined there today. Val d&#146;Or had been and home to many mining companies such as Bourlamaque, Siscoe, Sigma, Sullivan, Lamaque, Osisco and Northern Star Mining. The history of the town reflects the region&#146;s economic dependence on mining.  
[Ref. 1]</atom>
    <atom name="ArtConFunction">To protect wearer from exposure to dirt, grease, etc. and to enhance wearer's visibility; to identify wearer as employee.</atom>
    <atom name="ArtConTechnical">Example of personal gear worn by employees.
This coverall worn by Jean-Marie Fecteau.</atom>
    <atom name="ArtConCountry">Canada</atom>
    <atom name="ArtConProvinceState">Qu&#233;bec</atom>
    <atom name="ArtConAreaNotes">Used in Val -d'Or, at CANMET Experimental Mine site.</atom>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2010.0255.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2010.0255.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetFinish">Dark blue polyester-cotton blend coverall has silver metal zipper and snap closures; fluorescent green and silver reflective band of synthetic fabric trim sewn to legs, sleeves and torso back. White thread used to embroider text on coverall front.</atom>
    <atom name="NotNotes">Additional Remarks: Size: 48 T.
May have been worn with personal gear items [type specimens] 2010.0256-.0259.
* Dimensions: approx., as for coverall suspended from clothes hangar.</atom>
    <atom name="ArtRefWorksheet">Yes;:;Oui</atom>
    <atom name="ArtRefManual">No;:;Non</atom>
    <atom name="ArtRefSuppInfo">Yes;:;Oui</atom>
    <atom name="ArtRefManual">No;:;Non</atom>
    <atom name="ArtRefArticleNumber">6530-66</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <table name="ArtRefReferences_tab">
      <tuple>
        <atom name="ArtRefReferences">Acquisition Proposal (including Inventory] prepared by A. Adamek &amp; S. Tudor- in Supp. Info. file 2010.0254; ecopy attached to Acquisition Lot AW0009 Multimedia tab.</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2475</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">63.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">22.0</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">166.0</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">Dark blue polyester-cotton blend coverall has silver metal zipper and snap closures; fluorescent green and silver reflective band of synthetic fabric trim sewn to legs, sleeves and torso back. White thread used to embroider text on coverall front.</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">fibre;:;fibre</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">synthetic;:;synth&#233;tique</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">synthetic;:;synth&#233;tique</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
    </table>
    <table name="ArtCompMaterialCHINSpecific_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">cotton;:;coton</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">polyester;:;polyester</atom>
      </tuple>
    </table>
    <atom name="ConConditionStatus">Very Good;:;Tr&#232;s bonne</atom>
    <atom name="ConDateChecked">2012-06-07</atom>
    <atom name="CstmcAdmAcquisitionProposal">yes</atom>
    <atom name="SrcLotAcquisition">yes;:;oui</atom>
    <atom name="SrcPreviousCstmcNos">AW0009.11 pt</atom>
  </tuple>
  <!-- Row 2 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">2010.0155</atom>
    <atom name="ObjObjectName">Box;:;Boite</atom>
    <atom name="ObjPartNo">002</atom>
    <atom name="ObjPartNoSum">002</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Mining and Metallurgy;:;Mines et m&#233;tallurgie</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexGroup">Marine Transportation;:;Transports maritimes</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Petrochemical extraction;:;Extraction p&#233;trochimie</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexCategory">Diving;:;Plong&#233;e</atom>
      </tuple>
    </table>
    <atom name="ObjManufactureDate">circa;:;vers</atom>
    <atom name="ObjManufactureDateFrom">2010</atom>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Aqua Lung</atom>
      <atom name="NamOrganisationAcronym">Aqua Lung</atom>
      <atom name="AddPhysCountry">Unknown</atom>
    </tuple>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2010.0155.002.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2010.0155.002.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetMissing">none</atom>
    <atom name="ArtDetFinish">Brown cardboard box with white label.</atom>
    <atom name="NotNotes">.2 box was also the shipping box.</atom>
    <atom name="ArtRefWorksheet">Yes;:;Oui</atom>
    <atom name="ArtRefManual">No;:;Non</atom>
    <atom name="ArtRefSuppInfo">Yes;:;Oui</atom>
    <atom name="ArtRefOversized">No;:;Non</atom>
    <atom name="ArtRefManual">No;:;Non</atom>
    <atom name="ArtRefStillImages">No;:;Non</atom>
    <atom name="ArtRefArticleNumber">6389-75</atom>
    <atom name="ArtRefMultimedia">No;:;Non</atom>
    <atom name="ArtRefExternalDoc">No;:;Non</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">2421</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssAssessmentDate">2011-04-15</atom>
    <atom name="AssConditionReport">Yes;:;Oui</atom>
    <atom name="AssOilCoolantEtc">none</atom>
    <atom name="AssActionRequired">none</atom>
    <atom name="AssActionTaken">none</atom>
    <atom name="AssOperable">No;:;Non</atom>
    <atom name="AssRestored">No;:;Non</atom>
    <atom name="AssHazards">none</atom>
    <table name="ArtCompWandDValue_tab">
      <tuple>
        <atom name="ArtCompWandDValue">036.5</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">017.5</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDValue">009.0</atom>
      </tuple>
    </table>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">Cardboard</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">paper;:;papier</atom>
      </tuple>
    </table>
    <table name="ArtCompMaterialCHINSpecific_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINSpecific">cardboard;:;carton</atom>
      </tuple>
    </table>
    <atom name="ConConditionStatus">Good;:;Bonne</atom>
    <atom name="ConDateChecked">2011-03-29</atom>
    <atom name="CstmcAdmAcquisitionProposal">yes</atom>
    <table name="InfStatus_tab">
      <tuple>
        <atom name="InfStatus">No;:;Non</atom>
      </tuple>
    </table>
    <table name="InfInspectionDate0">
      <tuple>
        <atom name="InfInspectionDate">2011-04-15</atom>
      </tuple>
    </table>
    <table name="StaStable_tab">
      <tuple>
        <atom name="StaStable">Yes;:;Oui</atom>
      </tuple>
    </table>
    <table name="StaInspectionDate0">
      <tuple>
        <atom name="StaInspectionDate">2011-04-15</atom>
      </tuple>
    </table>
  </tuple>
  <!-- Row 3 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">2011.0006</atom>
    <atom name="ObjObjectName">Suit, survival</atom>
    <atom name="ObjObjectType">LARGE</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">MS2195</atom>
      </tuple>
    </table>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">001</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Mining and Metallurgy;:;Mines et m&#233;tallurgie</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Personal gear;:;Outillage personnel</atom>
      </tuple>
    </table>
    <atom name="ObjManufactureDateFrom">2011</atom>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Mustang Survival Corp.</atom>
      <atom name="NamOrganisationAcronym">Mustang</atom>
      <atom name="AddPhysCountry">Canada</atom>
    </tuple>
    <atom name="ArtConCanada">This artifact shows the latest step in the design of safety suits for the Canadian offshore petroleum industry. Exposure suits were first recommended by the Royal Commission, which was mandated to find out why the Ocean Ranger rig capsized, why no crew member was saved and how such accidents can be prevented in future.  Among the 66 recommendations, the Commission suggested that the use of exposure suits may have saved lives of the Ocean Ranger workers. 

This particular suit is an improved version of standard gear, developed in response to the crash of the Cougar Flight 91 in March 2009 on route to SeaRose FPSO and Hibernia. Only one person survived the crash. Robert Decker escaped the dark helicopter using the light attached to his survival suit. The suit started to leak by the time rescue arrived and Robert was entering the state of hypothermia. All passengers on the flight wore Helly Hansen suits. There were serious problems with the suits. To quote Decker&#146;s testimony: "These suits fit no one. Joke was one size fits no one." The locator beacons on the suits did not work. Passengers did not put on the hoods and gloves. One other person, Allison Maher made it to the surface, but she did not survive. 

The suits are regulated by Canada-Nova Scotia, and Canada-Newfoundland and Labrador Offshore Petroleum Boards. 

The first offshore rigs were erected in California at the turn of the 20th century in shallow water, close to the coast. The first true offshore oil well was drilled in 1947 in the Magnolia Creole field off the coast of Louisiana. In Canada, exploratory drilling dates back to the 1943, when the first well, Hillsborough No. 1, was drilled down 8 meters of water 13 km off the cost of PEI. The well was drilled from an artificial island made of wood cribbing, rock and concrete; it reached a depth of 4,479 metres, but neither oil nor natural gas was found. Test wells were drilled in the Beaufort Sea in 1966 and exploration off of British Columbia&#146;s coasts dates to 1958. Today Canada&#146;s offshore industry is concentrated on the Atlantic Ocean. In 1972 British Columbia imposed a moratorium on the offshore drilling on the Pacific Ocean which still stands. There are three active offshore oil production projects off the Atlantic Canadian coast: Hibernia, Terra Nova, and White Rose, from which 40% </atom>
    <atom name="ArtConFunction">To protect an offshore worker during a transport to and from a drilling platform.</atom>
    <atom name="ArtConTechnical">The survival suit is part of an integrated safety system designed to protect the lives of offshore petroleum workers while increasing the worker&#146;s chances of rescue in the event of an offshore accident.  The four part system includes training, a breathing apparatus (2010.0155), a locator beacon, and a survival suit. The survival suit&#146;s role in the system is to reduce the wearer&#146;s risk of hypothermia by protecting them from the elements, keeping the wearer afloat, and increasing the visibility of the survivor.

The Mustang Survival Suit (MS2195) is built to address the situations that a survivor of an offshore incident would face.  The suit has a clo value of 0.42, meaning that the wearer is insulated against hypothermia for up to 8 hours in 10*C in calm water.  Wearing a suit with a high clo value increases the length of time that rescuers have of finding survivors before hypothermia sets in.  Also built into the suit is flotation layer made up of air filled PVC foam which acts as the primary flotation for the suit as well as an insulating layer. The main flotation is supplemented by an inflatable neck and head support providing the wearer with some comfort and added buoyancy while waiting to be rescued. The survival suit shell is made of a bright orange fabric which is resistant to fading due to weathering and the effects of ultraviolet rays. The bright orange fabric increases the visibility of the wearer in the event of a rescue.</atom>
    <atom name="ArtConPeriod">New, never worn</atom>
    <atom name="ArtConCountry">Canada</atom>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2011.0006.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/2011.0006.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetFinish">Primarily orange synthetic fabric with black trim and interior. Synthetic zipper enclosures. Light reflective synthetic material at shoulders. Black neoprene at cuffs. Black synthetic fastener, velcro and metal snaps.</atom>
    <atom name="ArtRefWorksheet">Yes;:;Oui</atom>
    <atom name="ArtRefManual">No;:;Non</atom>
    <atom name="ArtRefSuppInfo">Yes;:;Oui</atom>
    <atom name="ArtRefOversized">No;:;Non</atom>
    <atom name="ArtRefManual">No;:;Non</atom>
    <atom name="ArtRefStillImages">No;:;Non</atom>
    <atom name="ArtRefArticleNumber">6396-173</atom>
    <atom name="ArtRefMultimedia">No;:;Non</atom>
    <atom name="ArtRefExternalDoc">No;:;Non</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <table name="ArtRefReferences_tab">
      <tuple>
        <atom name="ArtRefReferences">1) Trottier, Louise, &#201;valuation de la collection: Les combustibles fossiles au Canada, Mus&#233;e de la Science et de la technologie du Canada : Ottawa, 2002.</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">2) Babian, Sharon, &#147;Evidence from a Disaster: The Ocean Ranger Collection at the Canada Science and Technology Museum&#148; CSTM: unpublished.</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">3) Babian, Sharon, &#147;Supplementary Information: 850780 &#150; Archival Material &#150; Ocean Ranger&#148;, CSTM: unpublished.</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">4) Decker, Robert, Testimony before the Offshore Helicopter safety Inquiry in 2009.</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">5) McIntosh, Robert G. Petroleum industry in Canada since 1947, Ottawa: National Museum of Science and Technology, 1992.</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">6) Trade Lit: L48425; L48423; L48424</atom>
      </tuple>
      <tuple>
        <atom name="ArtRefReferences">7) Acquisition proposal in O:\Cons &amp; Coll Serv\Cons &amp; Coll Serv\Collection Services\SUPPINFO\Artifact\2011</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">1867</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <table name="ArtCompWandDUnit_tab">
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDUnit">cm</atom>
      </tuple>
    </table>
    <atom name="ArtCompGeneralDescription">Synthetic suit with synthetic zippers, enclosures and velcro. Metal snaps.</atom>
    <table name="ArtCompMaterialCHINGeneral_tab">
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">synthetic;:;synth&#233;tique</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompMaterialCHINGeneral">metal;:;m&#233;tal</atom>
      </tuple>
    </table>
    <atom name="ConConditionStatus">Excellent;:;Excellente</atom>
    <atom name="ConDateChecked">2011-05-04</atom>
    <atom name="CstmcAdmAcquisitionProposal">yes</atom>
  </tuple>
  <!-- Row 4 -->
  <tuple>
    <atom name="ObjObjectDiscipline">Artifact;:;Artefact</atom>
    <atom name="ObjCatalogueNumber">1980.0581</atom>
    <atom name="ObjObjectName">Meter, beta-gamma survey;:;Indicateur beta-gamma</atom>
    <atom name="ObjObjectType">GEIGER-MUELLER</atom>
    <table name="ObjModel_tab">
      <tuple>
        <atom name="ObjModel">EA-141BA</atom>
      </tuple>
    </table>
    <atom name="ObjSerialNumber">164</atom>
    <atom name="ObjPartNo">001</atom>
    <atom name="ObjPartNoSum">001</atom>
    <table name="ArtLexRank_tab">
      <tuple>
        <atom name="ArtLexRank">1</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">2</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexRank">3</atom>
      </tuple>
    </table>
    <table name="ArtLexGroup_tab">
      <tuple>
        <atom name="ArtLexGroup">Mining and Metallurgy;:;Mines et m&#233;tallurgie</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexGroup">Physics;:;Physique</atom>
      </tuple>
    </table>
    <table name="ArtLexCategory_tab">
      <tuple>
        <atom name="ArtLexCategory">Mineral exploration;:;Exploration mini&#232;re</atom>
      </tuple>
      <tuple>
        <atom name="ArtLexCategory">Atomic &amp; nuclear;:;Atomique et nucl&#233;aire</atom>
      </tuple>
    </table>
    <table name="ArtLexSubCategory_tab">
      <tuple>
        <atom name="ArtLexSubCategory">Measurement;:;Mesurage</atom>
      </tuple>
    </table>
    <tuple name="ObjManufacturerRef">
      <atom name="NamOrganisation">Electronic Associates Ltd.</atom>
      <atom name="NamOrganisationAcronym">Electronic</atom>
      <atom name="AddPhysCity">Willowdale</atom>
      <atom name="AddPhysCountry">Canada</atom>
      <atom name="AddPhysState">Ontario</atom>
    </tuple>
    <table name="ArtCompWandDMeasurement_tab">
      <tuple>
        <atom name="ArtCompWandDMeasurement">Length;:;longueur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Width;:;largeur</atom>
      </tuple>
      <tuple>
        <atom name="ArtCompWandDMeasurement">Height;:;hauteur</atom>
      </tuple>
    </table>
    <table name="MulMultiMediaRef_tab">
      <tuple>
        <table name="DocIdentifier_tab">
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1980.0581.001.aa.cs.jpg</atom>
          </tuple>
          <tuple>
            <atom name="DocIdentifier">http://source.techno-science.ca/images/1980.0581.001.aa.cs.thumb.jpg</atom>
          </tuple>
        </table>
      </tuple>
    </table>
    <atom name="ArtDetMissing">Batteries have been removed - Unknown quantites and voltages.</atom>
    <atom name="ArtDetFinish">CASING- BLUE/GREY; ROD- NICKEL PLATED</atom>
    <atom name="ArtRefSuppInfo">No;:;Non</atom>
    <atom name="ArtRefArticleNumber">6396-37</atom>
    <table name="ArtRefImage_tab">
      <tuple>
        <atom name="ArtRefImage">Digital image;:;Image digital</atom>
      </tuple>
    </table>
    <tuple name="LocCurrentLocationRef">
      <atom name="LocLevel1">On Loan</atom>
    </tuple>
    <atom name="LocIndependentlyMoveable">Yes;:;Oui</atom>
    <atom name="AssAssessmentDate">2010-05-05</atom>
    <atom name="AssConditionReport">No;:;Non</atom>
    <atom name="AssOilCoolantEtc">None</atom>
    <atom name="AssOperable">No;:;Non</atom>